apiVersion: batch/v1
kind: Job
metadata:
  name: mealie-restore
  namespace: utilities-priv
spec:
  template:
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 3000
        runAsGroup: 3000
        fsGroup: 3000
        seccompProfile:
          type: RuntimeDefault
      nodeSelector:
        kubernetes.io/hostname: yumi
      restartPolicy: Never
      volumes:
        - name: mealie-data
          hostPath:
            path: /var/mnt/mealie
            type: Directory
        - name: nfs-backup
          nfs:
            server: nfs.local.timo.be
            path: /mnt/FranzHopper/appdata/mealie
      containers:
        - name: restore
          image: ghcr.io/timoverbrugghe/k8s-restore:latest
          imagePullPolicy: Always
          stdin: false
          tty: false
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          env:
            - name: PUID
              value: "3000"
            - name: PGID
              value: "3000"
          volumeMounts:
            - name: mealie-data
              mountPath: /appdata
            - name: nfs-backup
              mountPath: /backup