---
apiVersion: v1
kind: ConfigMap
metadata:
  name: democratic-csi
  namespace: democratic-csi
  labels:
    app.kubernetes.io/name: democratic-csi
    app.kubernetes.io/instance: democratic-csi
data:
  extra-ca-certs: ""
