---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: truenas-iscsi
  labels:
    app.kubernetes.io/name: democratic-csi
    app.kubernetes.io/instance: democratic-csi
provisioner: org.democratic-csi.iscsi
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: Immediate

parameters:
  fsType: "ext4"
