apiVersion: batch/v1
kind: CronJob
metadata:
  name: bitwarden-export
  namespace: utilities-priv
spec:
  schedule: "0 2 * * *" # Runs daily at 2:00 AM
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            seccompProfile:
              type: RuntimeDefault
            fsGroup: 3000
          restartPolicy: OnFailure
          nodeSelector:
            kubernetes.io/hostname: yumi
          containers:
            - name: bitwarden-export
              image: ghcr.io/timoverbrugghe/bitwarden-export:latest # Replace with your container image
              stdin: false
              tty: false
              securityContext:
                allowPrivilegeEscalation: false
                runAsNonRoot: true
                runAsUser: 3000
                runAsGroup: 3000
                capabilities:
                  drop: ["ALL"]
                readOnlyRootFilesystem: true
              env:
                - name: BW_SERVER
                  value: https://bitwarden.kubernetes.timo.be
                - name: BW_APPID
                  valueFrom:
                    secretKeyRef:
                      name: bitwarden-export-secret
                      key: BW_APPID
                - name: BW_CLIENTID
                  valueFrom:
                    secretKeyRef:
                      name: bitwarden-export-secret
                      key: BW_CLIENTID
                - name: BW_CLIENTSECRET
                  valueFrom:
                    secretKeyRef:
                      name: bitwarden-export-secret
                      key: BW_CLIENTSECRET
                - name: BW_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: bitwarden-export-secret
                      key: BW_PASSWORD
              volumeMounts:
                - name: config
                  mountPath: /app/.config
                - name: nfs-export
                  mountPath: /backup
          volumes:
            - name: config
              emptyDir: {}
            - name: nfs-export
              nfs:
                server: nfs.local.timo.be
                path: /mnt/FranzHopper/appdata/bitwarden-export
