# Apply all these resources with `kubectl apply -k .` from the directory containing this file
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: ddclient
    namespace: utilities
    files:
      - ddclient.conf
    options:
      labels:
        app.kubernetes.io/name: ddclient

generatorOptions:
  disableNameSuffixHash: true

resources:
  - ddclient.yaml
