x-hardening-defaults: &hardening-defaults
  security_opt:
    - seccomp=default
    - no-new-privileges=true
  tty: false
  stdin_open: false
  logging:
    driver: json-file
    options:
      max-size: "50m"
      max-file: "5"

x-limits-light: &limits-light
  pids_limit: 512
  mem_limit: 512m
  cpus: 0.50

x-limits-medium: &limits-medium
  pids_limit: 512
  mem_limit: 1g
  cpus: 1.00

services:
  adguardhome:
    <<: [*hardening-defaults, *limits-medium]
    image: adguard/adguardhome
    container_name: adguardhome
    read_only: true
    restart: always
    networks:
      dockervlan:
        ipv4_address: ${ADGUARDHOME_IP_ADDRESS}
    volumes:
      - adguardhome-work:/opt/adguardhome/work
      - adguardhome-conf:/opt/adguardhome/conf
      - /var/lib/acme/timo.be:/etc/letsencrypt/live/timo.be

volumes:
  adguardhome-work:
  adguardhome-conf:

networks:
  dockervlan:
    name: dockervlan
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: "10.10.10.0/24"
          gateway: "10.10.10.1"