x-hardening-defaults: &hardening-defaults
  security_opt:
    - seccomp=default
    - no-new-privileges:true
  tty: false
  stdin_open: false
  logging:
    driver: json-file
    options:
      max-size: "50m"
      max-file: "5"

x-limits-heavy: &limits-heavy
  pids_limit: 512
  mem_limit: 2g
  cpus: 2.00

services:
  webtop-chrome:
    <<: [*hardening-defaults, *limits-heavy]
    image: lscr.io/linuxserver/webtop:latest
    container_name: webtop
    restart: always
    networks:
      - dockerproxy
    environment:
      - PUID=${PUID:-3000}
      - PGID=${PGID:-3000}
      - TZ=Europe/Brussels
      - SUBFOLDER=/ # optional
      - TITLE=Webtop # optional
    volumes:
      - webtop:/config
      - downloads:/downloads
    ports:
      - 12006:3000
      - 12007:3001
    shm_size: "1gb" # Increase shared memory for Chrome stability

volumes:
  webtop:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/mnt/FranzHopper/appdata/webtop"
  downloads:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/mnt/FranzHopper/downloads"

networks:
  dockerproxy:
    external: true
