apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: homepage
  namespace: utilities
  labels:
    app.kubernetes.io/name: homepage
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: homepage
