apiVersion: batch/v1
kind: CronJob
metadata:
  name: talos-upgrade-notification
  namespace: upgrade-notification
spec:
  # Run every Sunday at 4 AM
  schedule: "0 4 * * 0"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 60
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            seccompProfile:
              type: RuntimeDefault
          containers:
            - name: talos-upgrade-notification
              image: ghcr.io/timoverbrugghe/talos-upgrade-notification:latest
              stdin: false
              tty: false
              securityContext:
                allowPrivilegeEscalation: false
                runAsNonRoot: true
                readOnlyRootFilesystem: true
                capabilities:
                  drop: ["ALL"]
              env:
                - name: TALOS_NODE
                  value: "william.local.timo.be" # Set this to the name of the node you want to monitor
                - name: TALOS_ENDPOINT
                  value: "william.local.timo.be" # Set this to the API endpoint of the node
                - name: PUSHOVER_USER_KEY
                  valueFrom:
                    secretKeyRef:
                      name: pushover-secret
                      key: user_key
                - name: PUSHOVER_API_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: pushover-secret
                      key: api_token
              volumeMounts:
                - name: talosconfig
                  mountPath: /talosconfig
                  readOnly: true
                - name: tmp
                  mountPath: /tmp
          restartPolicy: OnFailure
          volumes:
            - name: talosconfig
              secret:
                secretName: talosconfig-secret
            - name: tmp
              emptyDir:
                sizeLimit: 512Mi