apiVersion: apps/v1
kind: Deployment
metadata:
  name: bootimus
  namespace: pxeboot
  labels:
    app.kubernetes.io/name: bootimus
  annotations:
    keel.sh/policy: force
    keel.sh/trigger: poll
    keel.sh/pollSchedule: "@every 24h"
    keel.sh/match-tag: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: bootimus
  template:
    metadata:
      labels:
        app.kubernetes.io/name: bootimus
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: bootimus
          image: garybowers/bootimus:latest
          imagePullPolicy: Always
          securityContext:
            capabilities:
              drop: ["ALL"]
              add: ["NET_BIND_SERVICE"]
          env:
            - name: BOOTIMUS_DATA_DIR
              value: /data
            - name: BOOTIMUS_TFTP_SINGLE_PORT
              value: "true"
            - name: BOOTIMUS_SERVER_ADDR
              value: "10.10.10.43"
            - name: BOOTIMUS_WINDOWS_SMB_ENABLED
              value: "true"
          ports:
            - containerPort: 445
              protocol: TCP
              name: smb
            - containerPort: 69
              protocol: UDP
              name: tftp
            - containerPort: 8080
              protocol: TCP
              name: http
            - containerPort: 8081
              protocol: TCP
              name: webui
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi

          startupProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 30
            successThreshold: 1

          livenessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          volumeMounts:
            - name: iso
              mountPath: /data/isos
      volumes:
        - name: iso
          nfs:
            server: nfs.local.timo.be
            path: /mnt/FranzHopper/isos/template/iso
